schema_version: 1

context:
  name: PyPDFForm
  version: "5.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/chinapandaman/PyPDFForm/archive/v${{ version }}.tar.gz
  sha256: 49acf59b882de91f4e1b1fc301d15bb4280572d014e6a402b0c9192a1898ec2d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - fonttools >=4.62.1,<5.0.0
    - pikepdf >=10.5.1,<11.0.0
    - pillow >=12.2.0,<13.0.0
    - pypdf >=6.11.0,<7.0.0
    - cryptography >=48.0.0,<49.0.0
    - reportlab >=4.5.0,<5.0.0

tests:
  - python:
      imports:
        - PyPDFForm
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: The Python library for PDF forms.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/chinapandaman/PyPDFForm

extra:
  recipe-maintainers:
    - thewchan
